<CalLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        TextInput:
            id: cal_input
            text: "0"
            halign: "right"
            font_size: 95
            size_hint:(1,0.12)

        GridLayout:
            cols: 4
            rows: 5

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "%"
                on_press: root.percentage()

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "<"
                on_press: root.backward()

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "C"
                on_press: root.clear()

            Button:
                size_hint: (0.2, 0.2)
                font_size:45
                text: "÷"
                on_press: root.math_sign("/")

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "7"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(7)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "8"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(8)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "9"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(9)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "X"
                on_press: root.math_sign("*")

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "4"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(4)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "5"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(5)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "6"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(6)

            Button:
                size_hint: (0.2, 0.2)
                font_size:65
                text: "-"
                on_press: root.math_sign("-")


            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "1"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(1)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "2"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(2)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "3"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(3)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "+"
                on_press: root.math_sign("+")

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "0"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.num_press(0)

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "."
                background_color: (157/255,157/255,157/255,1)
                on_press: root.dot()

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "(-)"
                background_color: (157/255,157/255,157/255,1)
                on_press: root.pos_neg()

            Button:
                size_hint: (0.2, 0.2)
                font_size:32
                text: "="
                on_press: root.equals()





